#!/usr/bin/env bash
# Idempotent configuration of every project service (Tasks B–F, Extensions A–E).
# Safe to run any number of times: files are only replaced when their content
# differs, services only restart when something changed, and every run ends in
# the same known-good "baseline" state. `make restore` is exactly this script.
# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"

APT='sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y -q -o DPkg::Lock::Timeout=300'

# ensure_pkg <node> <package>  -> prints "installed" if it had to install
ensure_pkg() {
  on "$1" "dpkg -s $2 >/dev/null 2>&1 || { $APT $2 >/dev/null 2>&1 && echo installed || echo FAILED; }"
}

# ensure_service <node> <unit> <changed?> [reload-or-restart|restart]: apply a changed
# config, else start if stopped (e.g. by a failure demo). Prints: ok or changed.
# dnsmasq must use "restart": its reload (SIGHUP) re-reads /etc/hosts, not dnsmasq.d/*.conf.
ensure_service() {
  if [ "$3" = changed ]; then
    on "$1" "sudo systemctl enable -q $2 2>/dev/null; sudo systemctl ${4:-reload-or-restart} $2"; echo changed
  else
    on "$1" "sudo systemctl enable -q $2 2>/dev/null; if systemctl is-active -q $2; then echo ok; else sudo systemctl start $2; echo changed; fi"
  fi
}

# ---- 0. base: /etc/cn/cn.env, shell prompt, cn-* helper commands -------------------
node_env() {   # node_env <node>
  local n="$1" unit="" port=""
  case "$n" in node-3) unit=backend-a; port=3001 ;; node-4) unit=backend-b; port=3002 ;; esac
  cat <<EOF
# /etc/cn/cn.env – generated by make converge
NODE_NAME=$n
ROLE="$(role_of "$n")"
ROLE_SHORT="$(short_of "$n")"
TEAM=$TEAM
DOMAIN=$DOMAIN
TTL=$TTL
PHASE=$PHASE
SELF_IP=$(ip_of "$n")
NODE1_IP=$NODE1_IP
NODE2_IP=$NODE2_IP
NODE3_IP=$NODE3_IP
NODE4_IP=$NODE4_IP
EDGE_IP=$EDGE_IP
STANDBY_EDGE_IP=$STANDBY_IP
DNS_SERVERS="$(dns_servers)"
RESOLV_MODE=$([ "$PHASE" = 1 ] && echo direct || echo stub)
BACKEND_UNIT=$unit
BACKEND_PORT=$port
EOF
}

shell_rc() {
  cat <<'EOF'
# /etc/cn/shell.sh – sourced from ~/.bashrc (installed by make converge)
. /etc/cn/cn.env
# marker printed after each command typed by `make live` (lets it know the command finished)
cn_done() { printf '\033[2m-- done #%s (exit %s) --\033[0m\n' "$1" "$2"; }
case "$NODE_NAME" in node-1) _c=36 ;; node-2) _c=35 ;; node-3) _c=33 ;; *) _c=32 ;; esac
PS1="\[\e[1;${_c}m\]$NODE_NAME\[\e[0m\]\[\e[2m\] ($ROLE_SHORT)\[\e[0m\]:\w\$ "
URL="https://app.$DOMAIN"
unset _c
EOF
}

step_base() {
  section "Base: node identity, shell, helper commands (cn-*)"
  local n
  for n in $NODES; do
    (
      local a b c h
      a="$(node_env "$n" | push_file "$n" /etc/cn/cn.env 644)"
      b="$(shell_rc | push_file "$n" /etc/cn/shell.sh 644)"
      c="$(on "$n" "grep -q /etc/cn/shell.sh ~/.bashrc && echo ok || { echo '[ -f /etc/cn/shell.sh ] && . /etc/cn/shell.sh' >> ~/.bashrc; echo changed; }")"
      h="$(COPYFILE_DISABLE=1 tar -cf - -C "$ROOT/node-bin" . | on "$n" "sudo sh -c '
            d=\$(mktemp -d); tar -xf - -C \$d 2>/dev/null; c=0
            for f in \$d/cn-*; do b=\$(basename \$f)
              cmp -s \$f /usr/local/bin/\$b || { install -m 755 \$f /usr/local/bin/\$b; c=\$((c+1)); }
            done; rm -rf \$d; echo \$c'")"
      if [ "$a$b$c" = okokok ] && [ "$h" = 0 ]; then report ok "$n" "cn.env, shell, helpers"
      else report changed "$n" "cn.env=$a shell=$b bashrc=$c helpers-updated=$h"; fi
    ) &
  done
  wait
}

# ---- 1. DNS servers (Task B, Extension A) ----------------------------------------
step_dns() {
  section "DNS: dnsmasq primary (node-1) + backup (node-3), app/api -> edge $EDGE_IP"
  local n st pkg ans ifc
  for n in node-1 node-3; do
    ifc="$(on "$n" cn-iface)"
    st="$(IFACE="$ifc" SELF_IP="$(ip_of "$n")" APP_IP="$EDGE_IP" render "$ROOT/config/dnsmasq.conf" \
          | push_file "$n" /etc/dnsmasq.d/cn-team.conf 644)"
    pkg="$(ensure_pkg "$n" dnsmasq)"
    [ "$pkg" = FAILED ] && { report failed "$n" "apt install dnsmasq"; continue; }
    [ -n "$pkg" ] && st=changed
    st="$(ensure_service "$n" dnsmasq "$st" restart)"
    ans="$(on "$n" "dig +short +time=2 +tries=2 @$(ip_of "$n") app.$DOMAIN" || true)"
    if [ "$ans" = "$EDGE_IP" ]; then report "$st" "$n" "dnsmasq on $(ip_of "$n"):53  app.$DOMAIN -> $ans"
    else report failed "$n" "dnsmasq does not answer app.$DOMAIN (got '${ans}') – sudo journalctl -u dnsmasq"; fi
  done
  [ "$FAILED" = 0 ] || die "DNS servers not working – not switching the clients to them"
}

# ---- 2. client resolvers (Task B) --------------------------------------------------
step_resolvers() {
  local servers mode; servers="$(dns_servers)"
  mode=$([ "$PHASE" = 1 ] && echo "direct: /etc/resolv.conf" || echo "stub: systemd-resolved cache")
  section "Resolvers: every machine asks [$servers]  (PHASE=$PHASE, $mode)"
  local n
  for n in $NODES; do
    (
      local st got
      st="$(on "$n" "sudo cn-resolver apply")"
      got="$(on "$n" "getent ahostsv4 app.$DOMAIN | awk 'NR==1{print \$1}'" || true)"
      if [ "$got" = "$EDGE_IP" ]; then report "$st" "$n" "resolver -> $servers   (app.$DOMAIN = $got)"
      else report failed "$n" "cannot resolve app.$DOMAIN through [$servers] (got '$got')"; fi
    ) &
  done
  wait
}

# ---- 3. backends (Task C) ----------------------------------------------------------
step_backends() {
  section "Backends: A on node-3:3001, B on node-4:3002 (systemd)"
  local spec n id port unit a b st i body
  for spec in "node-3 A 3001 backend-a" "node-4 B 3002 backend-b"; do
    # shellcheck disable=SC2086
    set -- $spec; n="$1"; id="$2"; port="$3"; unit="$4"
    a="$(push_file "$n" /opt/cn/backend.py 644 < "$ROOT/config/backend.py")"
    b="$(UNIT="$unit" BACKEND_ID="$id" PORT="$port" render "$ROOT/config/backend.service" \
         | push_file "$n" "/etc/systemd/system/$unit.service" 644)"
    st=ok; { [ "$a" = changed ] || [ "$b" = changed ]; } && st=changed
    if [ "$b" = changed ]; then on "$n" "sudo systemctl daemon-reload"; fi
    st="$(ensure_service "$n" "$unit" "$st")"
    body=""
    for i in 1 2 3 4 5 6; do
      body="$(on node-2 "curl -s --max-time 2 http://$(ip_of "$n"):$port/api/status" || true)"
      case "$body" in *"\"backend\": \"$id\""*) break ;; esac
      sleep 1
    done
    case "$body" in
      *"\"backend\": \"$id\""*) report "$st" "$n" "$unit on 0.0.0.0:$port  (reachable from the edge)" ;;
      *) report failed "$n" "$unit not reachable from node-2 – sudo journalctl -u $unit" ;;
    esac
  done
}

# ---- 4. TLS (Task E) ---------------------------------------------------------------
step_tls() {
  section "TLS: private CA + server certificate (on node-2), CA trusted everywhere"
  local st n
  st="$(on node-2 "sudo bash -s -- $TEAM $DOMAIN" < "$ROOT/scripts/remote/pki.sh")"
  report "$st" node-2 "CA '$TEAM Private CA' + cert for app/api.$DOMAIN (/etc/cn-pki)"
  mkdir -p "$ROOT/certs"
  on node-2 "sudo cat /etc/cn-pki/ca.crt"  > "$ROOT/certs/ca.crt"
  on node-2 "sudo cat /etc/cn-pki/tls.crt" > "$ROOT/certs/app.crt"
  for n in $NODES; do
    (
      local s
      s="$(push_file "$n" /usr/local/share/ca-certificates/cn-team-ca.crt 644 < "$ROOT/certs/ca.crt")"
      if [ "$s" = changed ]; then on "$n" "sudo update-ca-certificates >/dev/null 2>&1"; fi
      report "$s" "$n" "CA in the system trust store"
    ) &
  done
  wait
}

# ---- 5. edges (Task D + E, Extension E standby) --------------------------------------
step_edges() {
  section "Edges: nginx on node-2 (primary) and node-3 (standby), same config"
  local n pkg a b c d st code i
  for n in node-2 node-3; do
    pkg="$(ensure_pkg "$n" nginx)"
    [ "$pkg" = FAILED ] && { report failed "$n" "apt install nginx"; continue; }
    a="$(on node-2 "sudo cat /etc/cn-pki/tls.crt" | push_file "$n" /etc/nginx/cn-tls/tls.crt 644)"
    b="$(on node-2 "sudo cat /etc/cn-pki/tls.key" | push_file "$n" /etc/nginx/cn-tls/tls.key 600)"
    c="$(render "$ROOT/config/nginx-edge.conf" | push_file "$n" /etc/nginx/conf.d/cn-edge.conf 644)"
    d="$(on "$n" "if [ -e /etc/nginx/sites-enabled/default ]; then sudo rm -f /etc/nginx/sites-enabled/default; echo changed; else echo ok; fi")"
    st=ok; case "$pkg$a$b$c$d" in *changed*|*installed*) st=changed ;; esac
    if ! on "$n" "sudo nginx -t -q"; then report failed "$n" "nginx config test failed"; continue; fi
    st="$(ensure_service "$n" nginx "$st")"
    # a backend that was just restarted may still be marked down (fail_timeout 10 s)
    for i in 1 2 3 4 5 6 7 8 9 10 11 12; do
      code="$(on node-4 "curl -s -o /dev/null -w '%{http_code}' --max-time 5 --resolve app.$DOMAIN:443:$(ip_of "$n") $URL/api/status" || true)"
      [ "$code" = 200 ] && break; sleep 1
    done
    if [ "$code" = 200 ]; then report "$st" "$n" "nginx :443 TLS -> backends  (HTTPS check $code, certificate verified)"
    else report failed "$n" "HTTPS via $n returned '$code'"; fi
  done
}

# ---- clean: undo firewall rules left by a demo (cn-fw) or a practice fault ---------------
step_clean() {
  section "Clean: remove isolation / practice-fault firewall rules"
  local n
  for n in $NODES; do
    (
      local r
      r="$(on "$n" "sudo sh -c '
            c=ok
            if iptables -S INPUT 2>/dev/null | grep -q cn-isolation; then cn-fw off >/dev/null 2>&1; c=changed; fi
            if iptables -S 2>/dev/null | grep -q cn-fault; then
              iptables -S | grep -- cn-fault | sed \"s/^-A /-D /\" | while read -r x; do iptables \$x; done; c=changed
            fi
            iptables -S 2>/dev/null | grep -qE \"cn-fault|cn-isolation\" && c=failed
            echo \$c'")"
      report "$r" "$n" "no isolation or fault rules"
    ) &
  done
  wait
  rm -f "$GEN/last-fault"
}

# ---- 7. end-to-end verification ---------------------------------------------------------
step_verify() {
  section "Verify: the full path from both clients, by name, certificate checked"
  local c out a b n
  for n in $NODES; do on "$n" "sudo resolvectl flush-caches" || true; done
  for c in node-4 node-1; do
    out="$(on "$c" "for i in 1 2 3 4 5 6; do curl -s -o /dev/null --max-time 5 -w '%{http_code}:%header{x-backend} ' $URL/api/status; done" || true)"
    a="$(echo "$out" | tr ' ' '\n' | grep -c '^200:A$' || true)"; b="$(echo "$out" | tr ' ' '\n' | grep -c '^200:B$' || true)"
    if [ "$((a + b))" = 6 ] && [ "$a" -gt 0 ] && [ "$b" -gt 0 ]; then
      report ok "$c" "6/6 HTTPS requests OK, balanced A=$a B=$b"
    else report failed "$c" "unexpected results: $out"; fi
  done
}

cmd_all() {
  need_cluster
  mkdir -p "$GEN"; LOG="$GEN/converge.log"; : > "$LOG"
  COUNTS="$(mktemp)"; export COUNTS
  local t0; t0=$(date +%s)
  step_base; step_clean; step_dns; step_resolvers; step_backends; step_tls; step_edges; step_verify
  local ch fa
  ch="$(grep -c '^changed$' "$COUNTS" || true)"; fa="$(grep -c '^failed$' "$COUNTS" || true)"
  rm -f "$COUNTS"
  printf '\n%s%s changed, %s failed  (%ss)%s\n' "$B" "$ch" "$fa" "$(( $(date +%s) - t0 ))" "$RST"
  [ "$fa" = 0 ] || die "some checks failed (details above, log: $LOG)"
  printf '%sAll services up.%s  https://app.%s is served by node-2 -> A/B.   Next: make tmux  or  make live\n' "$GRN$B" "$RST" "$DOMAIN"
}

cmd_restore() { cmd_all; }

dispatch "$@"
