#!/usr/bin/env bash
# make form – collect the Phase 1 submission-form answers (A1–D3) from the REAL machines.
# Every command is run exactly as the form asks, on the machine it asks for, and the
# raw terminal output is saved. Result: evidence/form/FORM.md (paste-ready) plus the
# packet captures for Wireshark in evidence/form/.
# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"
need_cluster
export PHASE_OVERRIDE=1   # Phase 1: clients use the team DNS directly (dig shows SERVER 10.0.1.11)
PHASE=1
OUT="$EVID/form"; F="$OUT/FORM.md"
mkdir -p "$OUT"
D="$DOMAIN"; U="https://app.$D"

# block <node> <command>: print the prompt + command + real output as a code block
block() {
  printf '```\nubuntu@%s:~$ %s\n' "$1" "$2"
  ssh -n -F "$SSH_CFG" "$1" "bash -lc $(printf '%q' "$2")" 2>&1 | tr -d '\r' || true
  printf '```\n\n'
}
q() { on_q node-4 "$1" || true; }   # quiet value extraction on the client
step() { printf '  %s\n' "$*" >&2; }

section "Preparing: known-good Phase 1 state"
"$ROOT/scripts/converge.sh" all | grep -E 'failed|All services|ERROR' || true

section "Collecting the answers (about 1 minute)"
{
echo "# Phase 1 form – real terminal output ($TEAM, $(date '+%F %T'))"
echo
echo "Generated by \`make form\`. Every block below is the unedited output of the command on the"
echo "machine shown in its prompt. Texts marked **Draft** contain values taken from your capture;"
echo "rewrite them in your own words before submitting."
echo

# ---------------- A1 ----------------
step "A1 machine IPs and roles"
echo "## A1 – Machine IPs and roles"; echo
echo '```'
for n in $NODES; do
  ifc="$(on_q "$n" cn-iface || echo '?')"
  printf '%-30s %-10s (%s)   instance/hostname %s\n' "$(role_of "$n" | cut -d- -f1 | sed 's/ *$//') / $(short_of "$n"):" "$(ip_of "$n")" "$ifc" "$n"
done
echo '```'; echo
echo "Per machine (\`ip -4 -brief address\`):"; echo
for n in $NODES; do block "$n" 'hostname; ip -4 -brief address show $(cn-iface)'; done
echo "Instances in the AWS account (private VPC IPs) – also add a screenshot of the EC2 console:"; echo
echo '```'
echo "$ aws ec2 describe-instances --filters Name=tag:Project,Values=cn-project ..."
aws ec2 describe-instances --region "$REGION" \
  --filters Name=tag:Project,Values=cn-project Name=instance-state-name,Values=running \
  --query 'Reservations[].Instances[].[Tags[?Key==`Name`]|[0].Value,PrivateIpAddress,InstanceType,State.Name]' \
  --output table 2>&1 || echo "(AWS credentials expired – run make creds, then make form again)"
echo '```'; echo

# ---------------- A2 ----------------
step "A2 dnsmasq configuration"
echo "## A2 – dnsmasq configuration (node-1, /etc/dnsmasq.d/cn-team.conf)"; echo
block node-1 "grep -vE '^[[:space:]]*(#|\$)' /etc/dnsmasq.d/cn-team.conf"
echo "\`listen-address\` is node-1's LAN IP (not 127.0.0.1), so every machine on the LAN can use it."
echo "\`local-ttl=$TTL\` gives the answers a visible TTL of $TTL s."; echo

# ---------------- A3 / A4 ----------------
step "A3 dig from a client (node-4)"
echo "## A3 – dig from a client machine (node-4 = Mac 4, not the DNS server)"; echo
block node-4 "cat /etc/resolv.conf"
block node-4 "dig app.$D"
step "A4 dig @8.8.8.8"
echo "## A4 – dig @8.8.8.8 (public DNS does not know the private name)"; echo
block node-4 "dig @8.8.8.8 app.$D"

# ---------------- A5 ----------------
step "A5 ping every pair"
echo "## A5 – Ping between all machine pairs (private VPC IPs, machine to machine)"; echo
for n in $NODES; do block "$n" "cn-pingall"; done

# ---------------- B ----------------
step "B1 curl -v"
echo "## B1 – curl -v https://app.$D  (no -k, domain name)"; echo
block node-4 "curl -v https://app.$D"
step "B2 load balancing"
echo "## B2 – Load balancing: 6 consecutive requests"; echo
block node-4 "for i in {1..6}; do curl -s https://app.$D/api/status; echo; done"
echo "The same 6 requests, showing only the X-Backend response header:"; echo
block node-4 "for i in {1..6}; do curl -si https://app.$D/api/status | grep -i '^x-backend'; done"
step "B3 nginx configuration"
echo "## B3 – nginx configuration (node-2, /etc/nginx/conf.d/cn-edge.conf)"; echo
block node-2 "cat /etc/nginx/conf.d/cn-edge.conf"

# ---------------- C ----------------
step "C packet capture (one request, DNS + TCP + TLS)"
echo "## C – Packet capture (node-4)"; echo
echo "Raw summary (open \`evidence/form/client-dns-tcp-tls.pcap\` in Wireshark for screenshots;"
echo "for decrypted HTTP set Preferences → Protocols → TLS → key log file = \`evidence/form/tls-keys.log\`):"; echo
block node-4 "sudo cn-capture"
scp -q -F "$SSH_CFG" node-4:/tmp/cn-client.pcap "$OUT/client-dns-tcp-tls.pcap" 2>/dev/null || true
scp -q -F "$SSH_CFG" node-4:/tmp/cn-keys.log "$OUT/tls-keys.log" 2>/dev/null || true

T="sudo tshark -n -r /tmp/cn-client.pcap"
dq="$(q "$T -Y 'dns.flags.response==0 and dns.qry.name==\"app.$D\"' -T fields -E separator=' ' -e ip.src -e udp.srcport -e ip.dst -e udp.dstport 2>/dev/null | head -1")"
dr="$(q "$T -Y 'dns.flags.response==1 and dns.qry.name==\"app.$D\"' -T fields -E separator=' ' -e dns.a -e dns.resp.ttl 2>/dev/null | head -1")"
syn="$(q "$T -Y 'tcp.flags.syn==1 and tcp.flags.ack==0' -T fields -E separator=' ' -e ip.src -e tcp.srcport -e ip.dst -e tcp.dstport -e tcp.seq_raw 2>/dev/null | tail -1")"
sa="$(q "$T -Y 'tcp.flags.syn==1 and tcp.flags.ack==1' -T fields -E separator=' ' -e tcp.seq_raw -e tcp.ack_raw 2>/dev/null | tail -1")"
ch="$(q "$T -Y 'tls.handshake.type==1' -V 2>/dev/null | grep -m1 -oE 'Cipher Suites \(([0-9]+) suites\)' | grep -oE '[0-9]+'" | tail -1)"
sc="$(q "$T -Y 'tls.handshake.type==2' -V 2>/dev/null | grep -E '^ +Cipher Suite: ' | tail -1 | sed 's/^ *Cipher Suite: //; s/ (0x.*//'")"
ad="$(q "$T -Y tls.app_data 2>/dev/null | wc -l")"
set -- $dq; c_ip="${1:-?}"; c_port="${2:-?}"; d_ip="${3:-?}"
set -- $dr; a_ip="${1:-?}"; a_ttl="${2:-?}"
set -- $syn; s_ip="${1:-?}"; s_port="${2:-?}"; e_ip="${3:-?}"; e_port="${4:-?}"; s_isn="${5:-?}"
set -- $sa; sa_isn="${1:-?}"; sa_ack="${2:-?}"

echo "### C1 – DNS (filter: \`dns\`) – Draft"; echo
echo "Filter \`dns\`. **Query:** \"Standard query A app.$D\" from the client $c_ip, source port $c_port"
echo "(an ephemeral port chosen by the client), to our DNS server $d_ip on UDP port 53."
echo "**Response:** from $d_ip:53 back to $c_ip:$c_port, flags show a response with no error;"
echo "ANSWER: app.$D A $a_ip, TTL $a_ttl s. $a_ip is the edge (node-2), so the client will connect"
echo "there next. The TTL tells the client it may cache this answer for $a_ttl seconds."; echo

echo "### C2 – TCP three-way handshake (filter: \`tcp.flags.syn==1\`, then follow the stream) – Draft"; echo
echo "**SYN** from the client $s_ip:$s_port (ephemeral port) to $e_ip:$e_port (HTTPS),"
echo "initial sequence number $s_isn (Wireshark shows it relative as Seq=0)."
echo "**SYN-ACK** from $e_ip:$e_port: the server's own ISN $sa_isn and Ack=$sa_ack (client ISN + 1, relative Ack=1)."
echo "**ACK** from the client: Seq=1, Ack=1 – the connection is established before any TLS data is sent."
echo "The handshake gives a reliable, ordered, connection-oriented channel: both sides agree on starting"
echo "sequence numbers so lost or out-of-order data can be detected and resent."; echo

echo "### C3 – TLS handshake (filter: \`tls\`) – Draft"; echo
echo "Two requests were captured: one forced to TLS 1.2 (certificate visible) and one with TLS 1.3."
echo "**ClientHello** from $s_ip to $e_ip:443 with SNI app.$D, offering ${ch:-?} cipher suites and"
echo "TLS 1.3 / 1.2 as supported versions. **ServerHello** from $e_ip chooses ${sc:-?}."
echo "In the TLS 1.2 handshake the **Certificate** message is readable: subject CN=app.$D,"
echo "SAN app.$D and api.$D, issued by \"$TEAM Private CA\". Then **ChangeCipherSpec** – from"
echo "here on both sides encrypt. Everything after that is shown only as **Application Data** ($ad records):"
echo "the HTTP method, path, headers and JSON body are inside encrypted TLS records, so Wireshark cannot"
echo "read them without the session keys. (In TLS 1.3 even the certificate is already encrypted.)"; echo

# ---------------- D ----------------
step "D1 caching headers"
echo "## D1 – curl -sI https://app.$D/api/status"; echo
block node-4 "curl -sI https://app.$D/api/status"
echo "Conditional request with the ETag (bonus – 304 Not Modified), on the endpoint that both backends serve identically:"; echo
block node-4 "E=\$(curl -sI https://app.$D/api/cached | awk 'tolower(\$1)==\"etag:\"{print \$2}' | tr -d '\\r'); curl -sI -H \"If-None-Match: \$E\" https://app.$D/api/cached"

echo "## D2 – What Cache-Control tells the client – Draft"; echo
echo "\`Cache-Control: public, max-age=60\` means the response may be stored by the browser (and any"
echo "shared cache) and reused for 60 seconds without asking the server again. Within those 60 s the"
echo "client answers from its own copy and sends nothing. After 60 s the copy is stale: the client"
echo "revalidates by sending the ETag in an \`If-None-Match\` header. If the content has not changed the"
echo "server replies **304 Not Modified** with no body and the client keeps using its copy for another"
echo "60 s; if it changed, the server sends 200 with the new body and a new ETag."; echo

step "D3 failure demo: stop one backend (before / after / restore)"
echo "## D3 – Failure demonstration: Option A, stop one backend"; echo
loop="for i in {1..6}; do curl -s -o /dev/null -w '%{http_code} X-Backend: %header{x-backend}\n' https://app.$D/api/status; done"
echo "**(2) Before** – both backends answer in turn:"; echo
block node-4 "$loop"
echo "**Action** – stop Backend A on node-3:"; echo
block node-3 "sudo systemctl stop backend-a; systemctl is-active backend-a; sudo ss -lnt | grep ':3001 ' || echo 'nothing listens on port 3001 now'"
echo "**(3) After** – every request still succeeds, all served by B:"; echo
block node-4 "$loop"
echo "What the edge saw (node-2 error log):"; echo
block node-2 "sudo grep -E 'refused|failed' /var/log/nginx/cn-edge-error.log | grep 3001 | tail -2"
echo "**(5) Restore** – start Backend A again; after nginx's fail_timeout (10 s) it is used again:"; echo
block node-3 "sudo systemctl start backend-a; systemctl is-active backend-a"
sleep 12
block node-4 "$loop"
echo "**(4) Layer – Draft:** the application layer behind the edge (Layer 7, Backend A's HTTP service; at"
echo "Layer 4 its port 3001 now answers TCP connections with a reset). DNS, IP routing, TCP to the edge and"
echo "TLS were all unaffected. nginx's connection to $NODE3_IP:3001 was refused, so it retried the request on"
echo "Backend B (\`proxy_next_upstream\`) and marked A as down for 10 s (\`max_fails=1 fail_timeout=10s\`):"
echo "the client saw no error. Restored with \`systemctl start backend-a\`; round-robin resumed."; echo
} > "$F"

"$ROOT/scripts/converge.sh" restore >/dev/null 2>&1 || true
printf '\n%sDone:%s %s  (+ pcap and key log in evidence/form/)\n' "$GRN$B" "$RST" "${F#"$ROOT"/}"
